#!/usr/bin/env python3
import os
import sys
from analyzer import Analyzer
from helpers import get_user_timeline
from termcolor import colored


def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screen_name")
        return 1

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # get screen_name
    screenName = sys.argv[1].strip('@')

    # get tweets
    tweets = get_user_timeline(screenName, 50)

    # if screen_name doesn't exist, return error
    if tweets == None:
        sys.exit("User is private or doesn't exist")

    # analyse tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

    return 0


if __name__ == "__main__":
    main()
